@startuml Atividade
!theme toy
skinparam BackgroundColor #fff
scale 0.9

start
:Acessar site FleetMaster;
:Gerenciamento de veículos;
:Cadastrar veículo;
:Visualizar veículos cadastrado;
:Visualizar localização no Maps;
  if (Manutenção necessária?) then (sim)
    :Acionar empresa terceira; 
    stop
  else (não)
    :Ignorar;
    stop
        @enduml
