@startuml
left to right direction

actor "Usuário" as Usuario

usecase "Autenticado" as Autenticado
usecase "Sem Autenticação" as SemAutenticacao
Usuario --> Autenticado

usecase "Cadastrar veículos" as cadastroVeiculos
Autenticado--> cadastroVeiculos
usecase "Cadastrar motorista" as cadastroMotorista
Autenticado--> cadastroMotorista
usecase "Visualizar veículos cadastrado" as veiculosCadastrado
Autenticado--> veiculosCadastrado
usecase "Visualizar veículos Maps" as veiculosMaps
Autenticado --> veiculosMaps
usecase "Empresa 3a (Manutenção)" as manutencao
Autenticado--> manutencao

Usuario --> SemAutenticacao
usecase "Tela Login" as login
SemAutenticacao--> login
usecase "Portfólio" as portfolio
SemAutenticacao--> portfolio
@enduml
