@startuml
package "Componente" {

    [Usuário (Admin)] as painel
    [Usuário (Mobile)] as usuarioMobile
    
    [Cadastrar veículo] as veiculosCadastrados
    [Cadastrar Motorista] as motoristaCadastro
    [Manutenção veículo] as manutencao
    [Banco de Dados] as db

    [Banco de Dados (Terceiro)] as db2
    [Localização no Maps] as localizacao
    
    db2 ..> localizacao
    usuarioMobile ..> db2
    painel --> db2

    painel --> db
    db ..> veiculosCadastrados
    db ..> motoristaCadastro
    db ..> manutencao
}
@enduml
