@startuml

node "Web Servece" {
    node "Browser" {
        component "HTML5"
    }
}

node "Servidor" {
    component "Back-End"
}

node "Servidor de Banco de Dados" {
    database "NoSQL"
}

node "Celular" {
    component "Maps"
}

node "Servidor Localização (Terceiro)" {
    database "MySQL"
}

"Web Servece" --> "Servidor"
"Servidor" --> "Servidor de Banco de Dados"

"Celular" --> "Servidor Localização (Terceiro)"
"Servidor Localização (Terceiro)" --> "Web Servece"

@enduml
