@startuml
object Usuario {
    - id: 1
    - email: user@hotmail.com
    - senha: "123"
    - token: token123
}

object Motorista {
    - nomeCompleto: Matheus Oliveira
    - idade: "25"
    - sexo: masculino
    - CPF: "12345678912"
    - CNH: "12345678989"
}

object Veiculo {
    - id: 1
    - marca: Toyota
    - cor: preto
    - modelo: Corolla
    - ano: "2010"
    - kmRodado: "1250"
}

object LocalizacaoMaps {
    - latitude: 154
    - longitude: 135
}

object Empresa {
    - nome: Auto Peças
    - telefone: "123456"
    - endereco: "Rua Joao Teteu"
    - data: 05-15-2024T15:30:00Z
    - prestadorServico: true
}

Usuario -- Motorista
Motorista -- Veiculo
Veiculo -- LocalizacaoMaps
Veiculo -- Empresa
@enduml